# Generated by Django 3.2.8 on 2025-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lsdorganization',
            options={'ordering': ['name'], 'verbose_name': 'LSD Organization', 'verbose_name_plural': 'LSD Organizations'},
        ),
        migrations.AlterField(
            model_name='lsdsurvey',
            name='groupSelection',
            field=models.CharField(choices=[('低收入人群', '低收入人群'), ('失独家庭', '失独家庭'), ('残疾人群', '残疾人群'), ('困难家庭（低保、低编）', '困难家庭（低保、低编）'), ('援助证', '援助证'), ('都不是', '都不是')], max_length=50),
        ),
    ]
