# Generated by Django 3.2.8 on 2025-03-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0001_initial'),
    ]

    operations = [
    ]
