# Generated by Django 3.2.8 on 2025-04-23 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0002_auto_20250415_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsdsurvey',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='手机号码格式不正确', regex='^1[3-9]\\d{9}$')]),
        ),
    ]
