# Generated by Django 3.2.8 on 2025-03-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0002_auto_20250327_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsdsurvey',
            name='biopsy_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lsdsurvey',
            name='hpv_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lsdsurvey',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lsdsurvey',
            name='tct_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
