# Generated by Django 3.2.8 on 2025-03-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0004_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsdOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='代码')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lsd.lsdorganization', verbose_name='父级机构')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
                'db_table': 'lsd_organization',
                'ordering': ['code'],
            },
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
