# Generated by Django 5.1.4 on 2025-03-25 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2025, 3, 25, 0, 34, 35, 422319))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2025, 3, 25, 0, 34, 35, 422396))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
