# Generated by Django 3.2.8 on 2025-03-27 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_auto_20250325_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 7, 23, 5, 558087)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 7, 23, 5, 558101)),
        ),
    ]
