# Generated by Django 3.2.8 on 2025-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lungsurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lsdsurvey',
            options={'verbose_name': '蓝丝带问卷调查表', 'verbose_name_plural': '蓝丝带问卷调查表'},
        ),
        migrations.AlterField(
            model_name='lsdsurvey',
            name='_openId',
            field=models.CharField(max_length=100),
        ),
    ]
