# Generated by Django 3.2.8 on 2025-03-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lungsurvey', '0002_auto_20250325_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LsdSurvey',
        ),
    ]
